name: portlends
description: lend project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  flutter_chip_tags: ^1.0.4
  chips_choice_null_safety: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - images/jardim.jpg
  fonts:
    - family: SF-PRO
      fonts:
        - asset: ./fonts/sf-pro-display/SF-Pro-Display-Regular.ttf
        - asset: ./fonts/sf-pro-display/SF-Pro-Display-Bold.ttf
          weight: 700
        - asset: ./fonts/sf-pro-display/SF-Pro-Display-SemiboldItalic.ttf
          style: italic

    - family: SF-PRO-Medium
      fonts:
        - asset: ./fonts/sf-pro-display/SF-Pro-Display-Medium.ttf


